CREATE DATABASE IF NOT EXISTS formulario_db;
USE formulario_db;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  direccion VARCHAR(200) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  pais VARCHAR(100) NOT NULL,
  departamento VARCHAR(100) NOT NULL,
  estado_civil VARCHAR(50) NOT NULL,
  foto VARCHAR(200),
  edad VARCHAR(10) NOT NULL,
  descripcion TEXT NOT NULL,
  acepta_terminos TINYINT(1) DEFAULT 0 NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
